# Test TreeTrek 2021-05-12 at 06:00:05

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Data::Table::Text
      run: |
        sudo cpan install -T Data::Table::Text

    - name: Install GitHub::Crud
      run: |
        sudo cpan install -T Digest::SHA1

    - name: Install tree
      run: |
        sudo apt-get install -y tree

    - name: Test
      run: |
        perl lib/Tree/Trek.pm
